server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/edsandrof/ms-configs.git'
          default-label: 'master'


eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka/'
